### ISSUE TITLE
Any recommendation on how to serve Embedded files?

### ISSUE THREAD

**Issue by aaronloe** [donnyv/Nancy.BundleIt#1]
So far I've just been creating my BUndleItFiles by providing the path to the script/css file like this:
BundleItFile("Scripts/jquery.2.1.3.js");

Will this work if the file is an embedded resource & not physically present?

**Comment by donnyv** [comment]
No, i guess you don't want the host to have access to your source file?

**Comment by aaronloe** [comment]
That's correct. For security reasons, I would like all my javascript to be served from the self hosted dll, not from the file system.

**Comment by donnyv** [comment]
I can look at that and see whats involved. Can't promise anything though.

**Comment by aaronloe** [comment]
Don't worry about it. It's actually simpler to just write my own middleware to intercept the requests for any .js, .html, .css files and look them up in the embedded resources. Thanks anyways!
